### ISSUE TITLE
Wheel chokes can't be fully removed.

### ISSUE THREAD

**Issue by Megaf** [HHS81/c182s#293]
Title says it all. More details in the screenshots.

**choke on**
![image](https://user-images.githubusercontent.com/6201512/45092031-1da6e180-b10c-11e8-83cc-40ec0e1c6741.png)

**choke off**
![image](https://user-images.githubusercontent.com/6201512/45092041-25ff1c80-b10c-11e8-87de-4d6d9a723e3d.png)

**Comment by Megaf** [comment]
It just lowers a bit in the ground, but far from enough. Preventing aircraft to roll.

**Comment by HHS81** [comment]
I fixed that a few days ago...Can you tell me which aircraft state you used here?

**Comment by Megaf** [comment]
Wildo.

**Comment by Megaf** [comment]
I used ready for takeoff.

**Comment by Megaf** [comment]
Fixed

**Comment by Megaf** [comment]
Ok, bug still present, if you are at one airport with the chokes on, lets say EIDW, and move to EGAC, choke will not come fully off.

**Comment by Megaf** [comment]
1. Spawn at some airport
2. Apply Cold And Dark state
3. Move to another airport using Select Airport
4. Chokes can no longer be removed, it seems like they are duplicated.

![image](https://user-images.githubusercontent.com/6201512/45258857-de9cb880-b3b7-11e8-90b7-4d4afa287a16.png)

**Comment by hbeni** [comment]
This is clearly related in #337 which will be fixed by #338
